### ISSUE TITLE
PHP 8.4 compliance

### ISSUE THREAD

**Issue by cedric-anne** [sabre-io/event#123]
We are currently using the `sabre/dav` in an open source project and we want to make it fully compliant with PHP 8.4, and we cannot upgrade to `sabre/event:^6.0` because `sabre/dav` is not compatible with it.

If we provide a patch for it, would you accept to integrate it in a new 5.1.5 version ?

There is at least the following deprecation to fix:
```
Deprecated: Sabre\Event\Loop\instance(): Implicitly marking parameter $newLoop as nullable is deprecated, the explicit nullable type must be used instead in /var/www/glpi/vendor/sabre/event/lib/Loop/functions.php on line 133
```

**Comment by staabm** [comment]
I think these deprecations should be fixed with cs fixer over the whole codebase (maybe also other sabre/* repos).
since fixing this error is backwards compatible we could do it in the older versions :+1:

**Comment by cedric-anne** [comment]
> maybe also other sabre/* repos

I confirm that it affects multiple `sabre/*` components we use.

**Comment by phil-davis** [comment]
I will link all the various related PRs to this issue, and keep the issue open until all PHP 8.4 compliance has been done.

**Comment by phil-davis** [comment]
These repos have been updated:
- [x] event see PR #126 and release https://github.com/sabre-io/event/releases/tag/5.1.5
- [x] xml see PR https://github.com/sabre-io/xml/pull/285 and release https://github.com/sabre-io/xml/releases/tag/2.2.8
- [x] uri see PR https://github.com/sabre-io/uri/pull/116 - no release needed, it "just works"
- [ ] http
- [ ] vobject
- [ ] dav
- [ ] cache

**Comment by staabm** [comment]
Just want to say thank you ❤️ for working thru all the repo @phil-davis

**Comment by phil-davis** [comment]
Also to-do is to forward-port code changes from the old major-version branches in each repo to the later (current...) branches and release PHP 8.4 compatible code in those branches.

**Comment by phil-davis** [comment]
I have got all the various major release branches of the "small" repos up-to-date with all the tools (cs-fixer, phpstan) and with CI running PHP 8.4, and releases done.
So event, http, xml and uri are done.

Now that they all pass cleanly, I will move on to getting the CI sorted out for vobject, and make releases for each major branch of that. And then do the same for "dav" (which is at the top of the dependency tree).

**Comment by nickvergessen** [comment]
> - [ ] vobject

- Progress in https://github.com/sabre-io/vobject/pull/662

> - [ ] dav

- Was done in https://github.com/sabre-io/dav/pull/1556 but needs releasing (after vobject I guess)

**Comment by phil-davis** [comment]
Released https://github.com/sabre-io/vobject/releases/tag/4.5.6 today.
Hoping to follow-up all the things in dav tomorrow and get that released.

**Comment by nickvergessen** [comment]
Anything we can assist with?

**Comment by phil-davis** [comment]
I finally got around to it!
https://github.com/sabre-io/dav/releases/tag/4.7.0

**Comment by phil-davis** [comment]
If there are any other PHP 8.4 issues found, then please reopen and we can sort them out.

**Comment by nickvergessen** [comment]
Will update our CI and check if there are any issues there and on the test servers that deploy master/main

**Comment by phil-davis** [comment]
CI passed for owncloud https://github.com/owncloud/core/pull/41329
