### ISSUE TITLE
error in coroutine.php

### ISSUE THREAD

**Issue by tomas-nielsen** [sabre-io/event#53]
I have just downloaded sabre/event 5.0.2 through composer, but now everytime i try to use it, i get the following 2 errors:

    Warning: Unsupported declare 'strict_types' in vendor/sabre/event/lib/coroutine.php on line 1

    Parse error: syntax error, unexpected ':', expecting '{' in vendor/sabre/event/lib/coroutine.php on line 48

Any idea, how to fix this?

**Comment by staabm** [comment]
the version you downloaded requires php7. either update your php or use a older version of this library which supports php5.

**Comment by evert** [comment]
Pretty nuts that people are still running PHP 5 :/
