### ISSUE TITLE
Publishing a 5.x release?

### ISSUE THREAD

**Issue by TysonAndre** [sabre-io/event#79]
https://github.com/sabre-io/event/compare/5.1.0...master doesn't seem to have any breaking changes to the source code that would affect applications using this library - just changes to documentation, supported versions, tools for local developement, and supported php versions.

- PHP 8.0 is supported in composer.json, making sabre/event installable without `--ignore-platform-reqs`. PHP 8.0.0 stable will be released on November 26 (https://wiki.php.net/todo/php80) and this will make it easier for users to install applications using sabre/event with 8.0 betas/RCs 
- The README was updated

**Comment by staabm** [comment]
Will take care
