### ISSUE TITLE
What if I refuse using  Composer ?

### ISSUE THREAD

**Issue by kezenwa** [sabre-io/event#95]
Have gone through this library and want to give it a try BUT I have always avoided using Composer mainly because I love to know what's being loaded and what extra dependence gets installed.

not using Composer means I never get lazy.

Going through https://github.com/sabre-io/event/blob/master/composer.json , I see the only dependency is PHP . I know that means I could do manual installation BUT I just want to ask to be super extra sure.

Asking also because I'm actually more interested in your HTTP library which requires this library as dependency so I checked this out so I could install both manually

**Comment by staabm** [comment]
IMO refusing composer will lead you to a dead end
